language: go
go:
  - 1.7
branches:
  only:
    - master
cache:
  directories:
    - vendor
env:
  DEV_REGISTRY=quay.io
services:
  - docker
sudo: required
install:
  - make bootstrap
script:
  - make test docker-build
